### ISSUE TITLE
Conflict with similarly named `dismiss-notices.js` in other plugins

### ISSUE THREAD

**Issue by afragen** [collizo4sky/persist-dismissible-admin-notices#26] opened 2018-11-27 19:12 UTC
It seems there's at least one other plugin that uses the `dismiss-notice.js` file name. This is causing a conflict for at least one user. 
https://wordpress.org/support/topic/delete-notice-check-out-the-autoptimize-extra-settings-to-activate-this-option/page/6/#post-10922823

I think renaming the file would be easist solution, but problem could pop up again. If the JS can be namespaced that would be best.

**Comment by futtta** [comment] 2018-11-27 19:39
hmmm ... this would only be a problem if the files were both enqueued with the same handle and/ or if the JS in the files uses functions/ objects with the same name, right? because it should be perfectly possible to enqueue two JS files that are named the same but are on different paths?

**Comment by afragen** [comment] 2018-11-27 19:46
I haven’t searched through the other plugin to see how it’s enqueued, but I’d have to bet both are using the same handle. 

Perhaps simply changing the handle will work.

**Comment by afragen** [comment] 2018-11-27 20:01
They are already using different handles.

**Comment by futtta** [comment] 2018-11-27 20:04
Then it would be logically function/ object names (or the AJAX-url
configured) that clash?

**Comment by afragen** [comment] 2018-11-27 20:14
But there's the rub. There aren't really any function/object names. Both are focusing, in some way, on `button.notice-dismiss`. My JS isn't up to the task of even determining if this is the issue.

**Comment by afragen** [comment] 2018-11-27 20:18
I will say that the Woo plugin doesn't use any sort of nonce.

**Comment by futtta** [comment] 2018-11-27 20:29
I'll see if I can take a swing at it tomorrow (not the JS expert either
though) :-)

**Comment by w3guy** [comment] 2018-11-27 20:46
Two or more plugins can have the same file name if they have different handles.

@futtta let us know what you find.

**Comment by afragen** [comment] 2018-11-27 20:52
BTW, we don’t even know if this is the reproducible cause.

**Comment by w3guy** [comment] 2018-11-27 21:17
I am not sure this [https://wordpress.org/support/topic/delete-notice-check-out-the-autoptimize-extra-settings-to-activate-this-option/page/6/#post-10922823] is the cause. It could be the conflicting plugin was causing all admin ajax to fatal or something.

That's more likely the cause.

LEt's close this issue.

**Closed as completed** 2018-11-27 22:08 UTC

**Comment by futtta** [comment] 2018-11-28 09:09
OK, root cause indeed is in dismiss-notice.js of the other plugin, [which acts on each `.notice.is-dismissable`](https://plugins.trac.wordpress.org/browser/woocommerce-delivery-notes/trunk/includes/component/tracking-data/assets/js/dismiss-notice.js#L9) instead of only on it's own (as PAnD does by checking for `data-dismissable`). I'll create a support ticket on that plugin's WordPress support forum.
