### ISSUE TITLE
Parameter to ensure notice disappears after X times displayed even if not dismissed?

### ISSUE THREAD

**Issue by futtta** [collizo4sky/persist-dismissible-admin-notices#32] opened 2020-12-12 10:32 UTC
Although irregular [I still receive complaints from people who can't dismiss the notice](https://wordpress.org/support/topic/the-most-spam-plugin-i-installed-recently/), very likely due to JS issues, which results in them seeing the notice continuously, forever which I agree is very frustrating. So could we somehow add logic that auto-dismisses a notice after having been displayed X times?

**Comment by afragen** [comment] 2020-12-12 11:07
If there's a JS issue, likely from another plugin, shouldn't the idea be to fix that?

As you know the JS issue may not be in this framework or in your plugin, but possibly some other plugin entirely.

**Comment by futtta** [comment] 2020-12-12 12:19
theoretically; yes, but in reality JS-wise a lot can go wrong which pand
cannot prevent, which is why a fallback-mechanism to insure excessive
display of the notice would be a good idea.

**Comment by afragen** [comment] 2020-12-12 15:50
So a question. Just guessing here but since closing the notice creates a transient and this is the part that seems to be failing, how would we set up something that saves a transient, especially given that this is likely the root cause?

**Comment by futtta** [comment] 2020-12-12 16:16
If JS then the issue is with the AJAX call  not firing, so "long" before
the transient is involved?

**Comment by afragen** [comment] 2020-12-12 20:33
Somehow the solution would need to be modifiable by the dev as same number wouldn't work for everyone.

I'm thinking a filter set by dev.

**Comment by futtta** [comment] 2020-12-12 20:50
agreed. default 10 or 20 + a filter to allow changing?

**Comment by futtta** [comment] 2020-12-12 20:51
or default off (0) (= no change from current behavior) and a filter to
allow changing

**Comment by afragen** [comment] 2020-12-12 21:32
I don't have the bandwidth at the moment to think about how to enable this. I'm happy to help test a PR. 

I still think your user's problem will continue to cause problems for them, if it's not with your plugin it will be somewhere else. I would hope they would be willing to help debug this issue, but it seems that reviewing with a one star rating is simpler. 😞

As with most debugging, they should start by deactivating plugins, except for yours, to see when/if the issue disappears. If all other plugins are deactivated and issue persists, they should activate a default theme like TwentyTwenty.

**Comment by futtta** [comment] 2020-12-13 08:32
re. debugging for JS issues; that could help that particular user if he agrees to collaborate, but we know how fragile JS can be, there will always be issues for a small minority of users so a fallback "max display" mechanism to avoid frustration for those could help, no? ;-)

don't have a PR yet (bandwidth and all), but I do have a quick draft to show how logic *could* work, see https://gist.github.com/futtta/e671cbcee90f244a251e2c888317b425

I gave it a quick test ( code snippet `add_filter( 'pand_maximum_notice_display', function(){ return 5; } );`) and it does seem to work.

**Comment by afragen** [comment] 2020-12-14 20:50
It would seem that the user has found the issue and yes, it's a caching issue. Transients are an ideal solution to storing short term data but they do have problems with database caching, or more correctly not saving the data because of the caching.

**Comment by futtta** [comment] 2020-12-14 20:57
but we're not using transients any more?

**Comment by afragen** [comment] 2020-12-14 21:32
Yeah, I knew we switched away from them for a reason. Unfortunately there's no accounting for someone's specific cache set up and how it will effect individual parts of the database. Clearly this was a bit too much database caching.

**Comment by futtta** [comment] 2020-12-15 07:48
I tested with WP Optimize on my own blog and could not replicate the
problem by the way ... What do you think about the fallback mechanism of
limiting the amount of times a notice is displayed Andy?

**Comment by afragen** [comment] 2020-12-15 17:34
@futtta I need to review it. Mostly I need to make sure it only effects the unique dismissal. Hopefully I'll be able to review and test within the next week but work gets in the way.

**Comment by futtta** [comment] 2020-12-15 17:36
understand the lack of time perfectly, just ping me here when you've had
the chance :)

**Comment by w3guy** [comment] 2020-12-31 17:16
Making your own dismiss link with `.dismiss-this` class would fix conflicts like this. See #29

**Closed as completed by w3guy** 2020-12-31 17:16 UTC
